version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["./entrypoint.sh"]
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app  # for development. Remove in production to use only image
    expose:
      - "8000"
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - web
    expose:
      - "80"
    networks:
      - webnet

  reverse-proxy:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - web
    networks:
      - webnet

volumes:
  db-data:

networks:
  webnet:

