version: "3.8"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["./entrypoint.sh"]
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app  # for development hot reload
    ports:
      - "8000:8000"  # Expose Django backend directly to localhost
    networks:
      - webnet

volumes:
  db-data:

networks:
  webnet:

